baseURL = 'https://www.noobsec.net/'
languageCode = 'en-us'
title = 'Welcome to noobsec'
theme = 'hugo-theme-monochrome'
enableEmoji = 'true'

disqusShortname = "n00bsec"
googleAnalytics = "UA-171056200-1"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5