[[navbar]]
  identifier = "oscp"
  name = "OSCP"
  url = "#"
  weight = 5
  [[navbar]]
    identifier = "oscp_cheatsheet"
    name = "OSCP Cheatsheet"
    url = "/oscp-cheatsheet"
    parent = "oscp"
    weight = 1
  [[navbar]]
    identifier = "oscp_powerview"
    name = "OSCP AD Cheatsheet"
    url = "/powerview-cheatsheet"
    parent = "oscp"
    weight = 2
  [[navbar]]
    identifier = "oscp_journey"
    name = "OSCP Journey"
    url = "/oscp-journey"
    parent = "oscp"
    weight = 3
  [[navbar]]
    identifier = "hacking_oscp"
    name = "Hacking OSCP Certification"
    url = "/hack-oscp"
    parent = "oscp"
    weight = 4
  [[navbar]]
    identifier = "oscp_bof"
    name = "OSCP BOF"
    url = "/bof"
    parent = "oscp"
    weight = 5
[[navbar]]
  identifier = "whoami"
  name = "whoami"
  url = "/whoami/"
  weight = 6
